    //
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 07:31:25 PM CEST 
//
package pl.adamborowski.medcharts.assembly.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder
        = {
            "selection",
            "serie"
        })
@XmlRootElement(name = "assembly")
public class Assembly {

    @XmlElement(required = true)
    protected List<Selection> selection;
    @XmlElement(required = true)
    protected List<Serie> serie;

    public List<Selection> getSelection() {
        if (selection == null) {
            selection = new ArrayList<>();
        }
        return this.selection;
    }

    public List<Serie> getSerie() {
        if (serie == null) {
            serie = new ArrayList<>();
        }
        return this.serie;
    }
}
