//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 07:31:25 PM CEST 
//
package pl.adamborowski.medcharts.assembly.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * generated.pl.adamborowski.medcharts.assembly
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Assembly }
     *
     */
    public Assembly createAssembly() {
        return new Assembly();
    }

    /**
     * Create an instance of {@link Assembly.Serie }
     *
     */
    public Serie createAssemblySerie() {
        return new Serie();
    }

    /**
     * Create an instance of {@link Assembly.Serie.Overlay }
     *
     */
    public Overlay createAssemblySerieOverlay() {
        return new Overlay();
    }

    /**
     * Create an instance of {@link Assembly.Selection }
     *
     */
    public Selection createAssemblySelection() {
        return new Selection();
    }

    /**
     * Create an instance of {@link Assembly.Serie.Overlay.Line }
     *
     */
    public Overlay.Line createAssemblySerieOverlayLine() {
        return new Overlay.Line();
    }

    /**
     * Create an instance of {@link Assembly.Serie.Overlay.Mask }
     *
     */
    public Overlay.Mask createAssemblySerieOverlayMask() {
        return new Overlay.Mask();
    }

}
