//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 07:31:25 PM CEST 
//


package pl.adamborowski.medcharts.assembly.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated.pl.adamborowski.medcharts.assembly package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated.pl.adamborowski.medcharts.assembly
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Assembly }
     * 
     */
    public Assembly createAssembly() {
        return new Assembly();
    }

    /**
     * Create an instance of {@link Assembly.Serie }
     * 
     */
    public Assembly.Serie createAssemblySerie() {
        return new Assembly.Serie();
    }

    /**
     * Create an instance of {@link Assembly.Serie.Overlay }
     * 
     */
    public Assembly.Serie.Overlay createAssemblySerieOverlay() {
        return new Assembly.Serie.Overlay();
    }

    /**
     * Create an instance of {@link Assembly.Selection }
     * 
     */
    public Assembly.Selection createAssemblySelection() {
        return new Assembly.Selection();
    }

    /**
     * Create an instance of {@link Assembly.Serie.Overlay.Line }
     * 
     */
    public Assembly.Serie.Overlay.Line createAssemblySerieOverlayLine() {
        return new Assembly.Serie.Overlay.Line();
    }

    /**
     * Create an instance of {@link Assembly.Serie.Overlay.Mask }
     * 
     */
    public Assembly.Serie.Overlay.Mask createAssemblySerieOverlayMask() {
        return new Assembly.Serie.Overlay.Mask();
    }

}
