//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 07:31:25 PM CEST 
//
package pl.adamborowski.medcharts.assembly.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selection" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="serie" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="overlay" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="line" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
 *                                     &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="mask" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
 *                                     &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="selection" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#cc55ff" />
 *                 &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{
    "selection",
    "serie"
})
@XmlRootElement(name = "assembly")
public class Assembly
{

    @XmlElement(required = true)
    protected List<Assembly.Selection> selection;
    @XmlElement(required = true)
    protected List<Assembly.Serie> serie;

    /**
     * Gets the value of the selection property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the selection property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelection().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Assembly.Selection }
     *
     *
     */
    public List<Assembly.Selection> getSelection()
    {
        if (selection == null)
        {
            selection = new ArrayList<Assembly.Selection>();
        }
        return this.selection;
    }

    /**
     * Gets the value of the serie property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the serie property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSerie().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Assembly.Serie }
     *
     *
     */
    public List<Assembly.Serie> getSerie()
    {
        if (serie == null)
        {
            serie = new ArrayList<>();
        }
        return this.serie;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Selection
    {

        @XmlAttribute(name = "id")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "title")
        protected String title;

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getId()
        {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setId(String value)
        {
            this.id = value;
        }

        /**
         * Gets the value of the title property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTitle()
        {
            return title;
        }

        /**
         * Sets the value of the title property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTitle(String value)
        {
            this.title = value;
        }
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="overlay" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="line" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
     *                           &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="mask" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
     *                           &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="selection" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#cc55ff" />
     *       &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    {
        "overlay",
        "selection"
    })
    public static class Serie
    {

        @XmlElement(required = true)
        protected List<Assembly.Serie.Overlay> overlay;
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Selection selection;
        @XmlAttribute(name = "title")
        protected String title;
        @XmlAttribute(name = "source")
        protected String source;
        @XmlAttribute(name = "color")
        protected String color;
        @XmlAttribute(name = "alpha")
        protected Float alpha;
        @XmlAttribute(name = "treshold")
        protected Integer treshold;

        /**
         * Gets the value of the overlay property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the overlay property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOverlay().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Assembly.Serie.Overlay }
         *
         *
         */
        public List<Assembly.Serie.Overlay> getOverlay()
        {
            if (overlay == null)
            {
                overlay = new ArrayList<>();
            }
            return this.overlay;
        }

        /**
         * Gets the value of the selection property.
         *
         * @return possible object is {@link Object }
         *
         */
        public Selection getSelection()
        {
            return selection;
        }

        /**
         * Sets the value of the selection property.
         *
         * @param value allowed object is {@link Object }
         *
         */
        public void setSelection(Selection value)
        {
            this.selection = value;
        }

        /**
         * Gets the value of the title property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTitle()
        {
            return title;
        }

        /**
         * Sets the value of the title property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTitle(String value)
        {
            this.title = value;
        }

        /**
         * Gets the value of the source property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getSource()
        {
            return source;
        }

        /**
         * Sets the value of the source property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setSource(String value)
        {
            this.source = value;
        }

        /**
         * Gets the value of the color property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getColor()
        {
            if (color == null)
            {
                return "#cc55ff";
            } else
            {
                return color;
            }
        }

        /**
         * Sets the value of the color property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setColor(String value)
        {
            this.color = value;
        }

        /**
         * Gets the value of the alpha property.
         *
         * @return possible object is {@link Float }
         *
         */
        public float getAlpha()
        {
            if (alpha == null)
            {
                return 1.0F;
            } else
            {
                return alpha;
            }
        }

        /**
         * Sets the value of the alpha property.
         *
         * @param value allowed object is {@link Float }
         *
         */
        public void setAlpha(Float value)
        {
            this.alpha = value;
        }

        /**
         * Gets the value of the treshold property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public int getTreshold()
        {
            if (treshold == null)
            {
                return 0;
            } else
            {
                return treshold;
            }
        }

        /**
         * Sets the value of the treshold property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setTreshold(Integer value)
        {
            this.treshold = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="line" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
         *                 &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="mask" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
         *                 &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder =
        {
            "line",
            "mask"
        })
        public static class Overlay
        {

            @XmlElement(required = true)
            protected List<Assembly.Serie.Overlay.Line> line;
            @XmlElement(required = true)
            protected List<Assembly.Serie.Overlay.Mask> mask;
            @XmlAttribute(name = "source")
            protected String source;

            /**
             * Gets the value of the line property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a
             * <CODE>set</CODE> method for the line property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLine().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Assembly.Serie.Overlay.Line }
             *
             *
             */
            public List<Assembly.Serie.Overlay.Line> getLine()
            {
                if (line == null)
                {
                    line = new ArrayList<Assembly.Serie.Overlay.Line>();
                }
                return this.line;
            }

            /**
             * Gets the value of the mask property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a
             * <CODE>set</CODE> method for the mask property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMask().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Assembly.Serie.Overlay.Mask }
             *
             *
             */
            public List<Assembly.Serie.Overlay.Mask> getMask()
            {
                if (mask == null)
                {
                    mask = new ArrayList<Assembly.Serie.Overlay.Mask>();
                }
                return this.mask;
            }

            /**
             * Gets the value of the source property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getSource()
            {
                return source;
            }

            /**
             * Sets the value of the source property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setSource(String value)
            {
                this.source = value;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
             *       &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Line
            {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "color")
                protected String color;
                @XmlAttribute(name = "alpha")
                protected Float alpha;

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getName()
                {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setName(String value)
                {
                    this.name = value;
                }

                /**
                 * Gets the value of the color property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getColor()
                {
                    if (color == null)
                    {
                        return "#666666";
                    } else
                    {
                        return color;
                    }
                }

                /**
                 * Sets the value of the color property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setColor(String value)
                {
                    this.color = value;
                }

                /**
                 * Gets the value of the alpha property.
                 *
                 * @return possible object is {@link Float }
                 *
                 */
                public float getAlpha()
                {
                    if (alpha == null)
                    {
                        return 1.0F;
                    } else
                    {
                        return alpha;
                    }
                }

                /**
                 * Sets the value of the alpha property.
                 *
                 * @param value allowed object is {@link Float }
                 *
                 */
                public void setAlpha(Float value)
                {
                    this.alpha = value;
                }
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="#666666" />
             *       &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}float" default="1" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Mask
            {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "color")
                protected String color;
                @XmlAttribute(name = "alpha")
                protected Float alpha;
                @XmlAttribute(name = "importToSelection")
                @XmlIDREF
                @XmlSchemaType(name = "IDREF")
                protected Selection importToSelection = null;

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getName()
                {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setName(String value)
                {
                    this.name = value;
                }

                /**
                 * Gets the value of the color property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getColor()
                {
                    if (color == null)
                    {
                        return "#666666";
                    } else
                    {
                        return color;
                    }
                }

                /**
                 * Sets the value of the color property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setColor(String value)
                {
                    this.color = value;
                }

                /**
                 * Gets the value of the alpha property.
                 *
                 * @return possible object is {@link Float }
                 *
                 */
                public float getAlpha()
                {
                    if (alpha == null)
                    {
                        return 1.0F;
                    } else
                    {
                        return alpha;
                    }
                }

                /**
                 * Sets the value of the alpha property.
                 *
                 * @param value allowed object is {@link Float }
                 *
                 */
                public void setAlpha(Float value)
                {
                    this.alpha = value;
                }

                /**
                 * Gets the value of the importToSelection property.
                 *
                 * @return possible object is {@link Object }
                 *
                 */
                public Selection getImportToSelection()
                {
                    return importToSelection;
                }

                /**
                 * Sets the value of the importToSelection property.
                 *
                 * @param value allowed object is {@link Object }
                 *
                 */
                public void setImportToSelection(Selection value)
                {
                    this.importToSelection = value;
                }
            }
        }
    }
}
